variables:
  PYTHON3: "C:\\python37\\python.exe"
  PYTHON2: "C:\\python27\\python.ex3"
alpha:
  type: deploy
  tags:
    - windows
  script:
    - $PYTHON3 -m pip install --upgrade pip
    - $PYTHON3 -m pip install --upgrade -r requirements.txt
    - cd src
    - $PYTHON3 -m pyinstaller main.spec
    - cd ..
    - cd scripts
    - $PYTHON3 prepare_zipversion.py
    - cd ..
    - move src\music_dl.zip music_dl.zip
  only:
    - master
  artifacts:
    paths:
    - music_dl.zip
    name: music_dl
    expire_in: 1 week
