variables:
  PYTHON3_32: "C:\\python37-32\\python.exe"
  PYTHON3_64: "C:\\python37-64\\python.exe"
  NSIS: "C:\\nsis\\makensis.exe"

### Stage list
# Build: This will be the main stage generating stuff in the dist folder. Jobs present in this stage will run py2exe or pyinstaller files accordingly.
# pack: Jobs in this stage will take the dist folder and zip it or generate an exe file.
stages:
    - test
    - build
    - pack

.configure_environment: &configure_environment
  tags:
    - windows10
  before_script:
    - '&$env:PYTHON3_32 -V'
    - '&$env:PYTHON3_32 -m pip install --upgrade pip'
    - '&$env:PYTHON3_32 -m pip install --upgrade -r requirements.txt'

test:
  <<: *configure_environment
  stage: test
  tags:
    - windows10
  script:
    - cd src
    - '&$env:PYTHON3_32 -m coverage run run_tests.py'
    - '&$env:PYTHON3_32 -m coverage report --omit="test*"'
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - master

public:
  <<: *configure_environment
  stage: build
  script:
    - cd src
    - '&$env:PYTHON3_32 setup.py build'
    - '&$env:NSIS installer.nsi'
    - cd ..
    - move src\music_dl* .
    - cd scripts
    - '&$env:PYTHON3_32 prepare_zipversion.py'
    - cd ..
    - move src\music_dl.zip music_dl.zip
  only:
    - master