# Declare some variables dependent on the operating system where the runner is installed.
# This CI file assumes we install everything in C:\ (Python 2.7, 3.7 and Nsis).
variables:
  PYTHON3: "C:\\python37\\python.exe"
  PYINSTALLER: "C:\\python37\\scripts\\pyinstaller.exe"
  NSIS: "C:\\nsis\\makensis.exe"
  PYTHON2: "C:\\python27\\python.exe"

### Stage list
# Build: This will be the main stage generating stuff in the dist folder. Jobs present in this stage will run py2exe or pyinstaller files accordingly.
# pack: Jobs in this stage will take the dist folder and zip it or generate an exe file.
stages:
    - build
    - pack

# Python 3 version. This is generated under Windows server 2016 Standard edition.
build_py3:
  stage: build
  tags:
    - windows10
  before_script:
    - '%PYTHON3% -m pip install --upgrade pip'
    - '%PYTHON3% -m pip install --upgrade -r requirements.txt'
  script:
    - cd src
    - '%PYINSTALLER% main.spec'
  only:
    - master
    - tags
    - schedule_pipelines
  # Make the dist folder available to other jobs.
  artifacts:
    paths:
    - src\\dist
    expire_in: 15 mins

zip_py3:
  stage: pack
  tags:
    - windows10
  only:
    - master
    - tags
    - schedule_pipelines
  dependencies:
    - build_py3
  script:
    - cd scripts
    - '%PYTHON3% prepare_zipversion.py'
    - cd ..
    - move src\music_dl.zip music_dl.zip
  artifacts:
    paths:
    - music_dl.zip
    expire_in: 1 hour

build_setup:
  stage: pack
  tags:
    - windows10
  only:
    - master
    - tags
    - schedule_pipelines
  dependencies:
    - build_py3
  script:
    - cd src
    - '%NSIS% installer.nsi'
    - cd ..
    - move src\music_dl* .
  artifacts:
    paths:
    - "music_dl_*"
    name: music_dl
    expire_in: 1 day

build_py2:
  stage: build
  tags:
    - windows7
  before_script:
    - '%PYTHON2% -m pip install --upgrade pip'
    - '%PYTHON2% -m pip install --upgrade -r requirements.txt'
    - '%PYTHON2% -m pip install --upgrade pypubsub==3.3.0 PySocks win_inet_pton'
  script:
    - cd src
    - '%PYTHON2% setup.py py2exe'
  # Make the dist folder available to other jobs.
  artifacts:
    paths:
    - src\\dist
    expire_in: 15 mins
  only:
    - master
    - tags
    - schedule_pipelines

zip_py2:
  stage: pack
  tags:
    - windows7
  only:
    - master
    - tags
    - schedule_pipelines
  dependencies:
    - build_py2
  script:
    - cd scripts
    - '%PYTHON2% prepare_zipversion.py'
    - cd ..
    - move src\music_dl.zip music_dl_py2.zip
  artifacts:
    paths:
    - music_dl_py2.zip
    expire_in: 1 hour